export enum AppEvents {
    SET_ACTION = "APP/SET_ACTION",
    SET_SHOPPING_LIST = "APP/SET_SHOPPING_LIST",
    GET_LIST_DATA = "APP/GET_LIST_DATA",
    SET_LOADING_STATE= "APP/SET_LOADING_STATE"
  }

  